### ISSUE TITLE
Move  resources to src/main/resources?

### ISSUE THREAD

**Issue by k-wall** [tinaselenge/realtime-analytics#2]
I've not tried this, but I suspect if you want to try this on the real cluster, you'll need to make sure that the data is available on in the JAR.  Moving it to the classpath might help.

https://github.com/tinaselenge/flink-sample-apps/blob/517e84bfc3a0822df9e3ea286c793fa1bd82aab0/src/main/java/flink/realtimeanalyticsapp/RetailSalesStreamingOperations.java#L60

**Comment by tinaselenge** [comment]
thanks @k-wall! It's done now.
